/**
 * Catálogo central de permissões.
 * Mantenha sincronizado com supabase/seeds/permissions_and_roles.sql.
 */

export const MODULES = Object.freeze({
  DASHBOARD: 'dashboard',
  CUSTOMERS: 'customers',
  SUPPLIERS: 'suppliers',
  PRODUCTS: 'products',
  INVENTORY: 'inventory',
  ORDERS: 'orders',
  FINANCE: 'finance',
  REPORTS: 'reports',
  USERS: 'users',
  ROLES: 'roles',
  SETTINGS: 'settings',
});

export const ACTIONS = Object.freeze({
  READ: 'read',
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
  INVITE: 'invite',
  REMOVE: 'remove',
  MOVE: 'move',
  ADJUST: 'adjust',
  CANCEL: 'cancel',
  REFUND: 'refund',
  EXPORT: 'export',
});

const p = (module, action) => `${module}.${action}`;

export const PERMISSIONS = Object.freeze({
  DASHBOARD_READ: p(MODULES.DASHBOARD, ACTIONS.READ),

  CUSTOMERS_READ: p(MODULES.CUSTOMERS, ACTIONS.READ),
  CUSTOMERS_CREATE: p(MODULES.CUSTOMERS, ACTIONS.CREATE),
  CUSTOMERS_UPDATE: p(MODULES.CUSTOMERS, ACTIONS.UPDATE),
  CUSTOMERS_DELETE: p(MODULES.CUSTOMERS, ACTIONS.DELETE),

  SUPPLIERS_READ: p(MODULES.SUPPLIERS, ACTIONS.READ),
  SUPPLIERS_CREATE: p(MODULES.SUPPLIERS, ACTIONS.CREATE),
  SUPPLIERS_UPDATE: p(MODULES.SUPPLIERS, ACTIONS.UPDATE),
  SUPPLIERS_DELETE: p(MODULES.SUPPLIERS, ACTIONS.DELETE),

  PRODUCTS_READ: p(MODULES.PRODUCTS, ACTIONS.READ),
  PRODUCTS_CREATE: p(MODULES.PRODUCTS, ACTIONS.CREATE),
  PRODUCTS_UPDATE: p(MODULES.PRODUCTS, ACTIONS.UPDATE),
  PRODUCTS_DELETE: p(MODULES.PRODUCTS, ACTIONS.DELETE),

  INVENTORY_READ: p(MODULES.INVENTORY, ACTIONS.READ),
  INVENTORY_MOVE: p(MODULES.INVENTORY, ACTIONS.MOVE),
  INVENTORY_ADJUST: p(MODULES.INVENTORY, ACTIONS.ADJUST),

  ORDERS_READ: p(MODULES.ORDERS, ACTIONS.READ),
  ORDERS_CREATE: p(MODULES.ORDERS, ACTIONS.CREATE),
  ORDERS_UPDATE: p(MODULES.ORDERS, ACTIONS.UPDATE),
  ORDERS_CANCEL: p(MODULES.ORDERS, ACTIONS.CANCEL),
  ORDERS_REFUND: p(MODULES.ORDERS, ACTIONS.REFUND),

  FINANCE_READ: p(MODULES.FINANCE, ACTIONS.READ),
  FINANCE_CREATE: p(MODULES.FINANCE, ACTIONS.CREATE),
  FINANCE_UPDATE: p(MODULES.FINANCE, ACTIONS.UPDATE),
  FINANCE_DELETE: p(MODULES.FINANCE, ACTIONS.DELETE),

  REPORTS_READ: p(MODULES.REPORTS, ACTIONS.READ),
  REPORTS_EXPORT: p(MODULES.REPORTS, ACTIONS.EXPORT),

  USERS_READ: p(MODULES.USERS, ACTIONS.READ),
  USERS_INVITE: p(MODULES.USERS, ACTIONS.INVITE),
  USERS_UPDATE: p(MODULES.USERS, ACTIONS.UPDATE),
  USERS_REMOVE: p(MODULES.USERS, ACTIONS.REMOVE),

  ROLES_READ: p(MODULES.ROLES, ACTIONS.READ),
  ROLES_CREATE: p(MODULES.ROLES, ACTIONS.CREATE),
  ROLES_UPDATE: p(MODULES.ROLES, ACTIONS.UPDATE),
  ROLES_DELETE: p(MODULES.ROLES, ACTIONS.DELETE),

  SETTINGS_READ: p(MODULES.SETTINGS, ACTIONS.READ),
  SETTINGS_UPDATE: p(MODULES.SETTINGS, ACTIONS.UPDATE),
});

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
